import React, { useState, useEffect } from 'react';
import { 
  BookOpen, 
  Search, 
  Clock, 
  Heart, 
  Database,
  ExternalLink,
  Facebook,
  Twitter,
  Linkedin,
  Phone,
  Mail,
  Download,
  Smartphone
} from 'lucide-react';
import { generateDailyDevotional, searchPastorChrisBooks, getFormattedDate } from './services/geminiService';
import { DevotionalContent, Book, SocialPlatform } from './types';
import PrayerOverlay from './components/PrayerOverlay';
import GalleryAndShare from './components/GalleryAndShare';

type View = 'daily' | 'books';

function App() {
  const [currentView, setCurrentView] = useState<View>('daily');
  const [devotional, setDevotional] = useState<DevotionalContent | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [timerSeconds, setTimerSeconds] = useState(300);
  const [isTimerActive, setIsTimerActive] = useState(false);
  const [showPrayer, setShowPrayer] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<Book[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [showNotification, setShowNotification] = useState<{message: string, type: 'social' | 'admin'} | null>(null);

  const formattedDate = getFormattedDate();
  const adminEmail = "abrahammartin5858@gmail.com";
  const rhapsodyBannerUrl = "https://rhapsodyofrealities.b-cdn.net/give.rhapsodyofrealities.org/new_lingual_banner.png";
  const backgroundImageUrl = "https://tse2.mm.bing.net/th/id/OIP.REMuCZYQVu6axFNLWqG5XwHaDu?pid=Api&P=0&h=220";
  const pastorChrisImageUrl = "https://flatimes.com/wp-content/uploads/2024/10/Pastor-Chris-O.jpg";

  useEffect(() => {
    const fetchDaily = async () => {
      setIsLoading(true);
      const data = await generateDailyDevotional(formattedDate);
      setDevotional(data);
      setIsLoading(false);
      setIsTimerActive(true);
    };
    fetchDaily();
  }, [formattedDate]);

  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (isTimerActive && timerSeconds > 0) {
      interval = setInterval(() => {
        setTimerSeconds((prev) => prev - 1);
      }, 1000);
    } else if (timerSeconds === 0 && isTimerActive) {
      setIsTimerActive(false);
      setShowPrayer(true);
    }
    return () => clearInterval(interval);
  }, [isTimerActive, timerSeconds]);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;
    setIsSearching(true);
    setCurrentView('books');
    const results = await searchPastorChrisBooks(searchQuery);
    setSearchResults(results);
    setIsSearching(false);
  };

  const handleDevotionalShare = (platform: SocialPlatform) => {
    if (!devotional) return;
    const url = window.location.href; 
    const text = `Read today's Rhapsody of Realities: "${devotional.title}"`;
    const fullText = `${text}\n\n${devotional.scripture}\n\nRead more at: ${url}`;
    let shareLink = '';
    switch (platform) {
      case SocialPlatform.Facebook: shareLink = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`; break;
      case SocialPlatform.Twitter: shareLink = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`; break;
      case SocialPlatform.WhatsApp: shareLink = `https://api.whatsapp.com/send?text=${encodeURIComponent(fullText)}`; break;
      case SocialPlatform.LinkedIn: shareLink = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`; break;
      case SocialPlatform.Email: shareLink = `mailto:?subject=${encodeURIComponent(devotional.title)}&body=${encodeURIComponent(fullText)}`; break;
    }
    if (shareLink) window.open(shareLink, '_blank', 'width=600,height=400');
    setTimeout(() => setShowNotification({ message: `Shared on ${platform}!`, type: 'social' }), 2000);
  };

  const handleAdminDatabaseExport = () => {
    const subject = encodeURIComponent("THE LAST MAN - User Database Export");
    const body = encodeURIComponent("Database generated by THE LAST MAN App.");
    window.location.href = `mailto:${adminEmail}?subject=${subject}&body=${body}`;
    setShowNotification({ message: "Admin notified.", type: 'admin'});
  };

  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  };

  return (
    <div className="min-h-screen flex flex-col font-sans bg-fixed bg-cover bg-center text-gray-900" style={{ backgroundImage: `url("${backgroundImageUrl}")` }}>
      <div className="flex flex-col min-h-screen bg-royal-900/60 backdrop-blur-[2px]">
        {showNotification && (
          <div className="fixed top-4 left-1/2 transform -translate-x-1/2 z-[100] w-11/12 max-w-md animate-in slide-in-from-top duration-500">
            <div className={`p-4 rounded-xl shadow-2xl border flex items-start gap-3 ${showNotification.type === 'social' ? 'bg-royal-900 text-white border-royal-700' : 'bg-gold-500 text-black border-gold-600'}`}>
              {showNotification.type === 'social' ? <Heart className="fill-red-500 text-red-500 shrink-0" /> : <Database className="shrink-0"/>}
              <div className="flex-1"><p className="text-sm leading-tight">{showNotification.message}</p></div>
              <button onClick={() => setShowNotification(null)} className="hover:opacity-70">×</button>
            </div>
          </div>
        )}

        <header className="bg-royal-950/95 backdrop-blur-md text-white sticky top-0 z-40 shadow-xl border-b border-gold-600">
          <div className="container mx-auto px-4 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-3 cursor-pointer" onClick={() => setCurrentView('daily')}>
              <div className="bg-gold-500 p-2 rounded-lg text-royal-950"><BookOpen size={28} /></div>
              <div>
                <h1 className="text-2xl font-serif font-black tracking-widest text-gold-500">THE LAST MAN</h1>
                <p className="text-[10px] text-royal-200 hidden md:block italic">"The life-changing truths in this last days..."</p>
              </div>
            </div>
            <form onSubmit={handleSearch} className="flex-1 max-w-md">
              <div className="relative group">
                <input type="text" placeholder="Search Rhapsody..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full bg-royal-900/80 border border-royal-700 rounded-full py-2 pl-10 pr-4 text-sm text-white placeholder-royal-300 focus:outline-none focus:border-gold-500" />
                <Search className="absolute left-3 top-2.5 text-royal-400" size={18} />
              </div>
            </form>
            <div className="flex items-center gap-4">
              <button onClick={handleAdminDatabaseExport} className="hidden md:flex items-center gap-1 text-xs text-royal-300 hover:text-white transition-colors"><Database size={14} />Admin</button>
              <div className="flex items-center gap-2 bg-royal-900/80 px-3 py-1 rounded-full border border-royal-800">
                <Clock size={16} className="text-gold-500" />
                <span className="font-mono text-sm">{formatTime(timerSeconds)}</span>
              </div>
            </div>
          </div>
        </header>

        <main className="flex-grow container mx-auto px-4 py-8">
          {currentView === 'daily' && (
            <div className="max-w-4xl mx-auto">
              {isLoading ? (
                <div className="flex flex-col items-center justify-center py-20 bg-white/10 backdrop-blur-sm rounded-2xl"><div className="animate-spin rounded-full h-16 w-16 border-t-4 border-gold-500 mb-4"></div><p className="text-white font-serif">Loading Rhapsody...</p></div>
              ) : devotional ? (
                <div className="grid md:grid-cols-3 gap-8">
                  <div className="md:col-span-2 space-y-6">
                    <article className="bg-white/95 backdrop-blur-sm p-8 rounded-2xl shadow-xl border-t-4 border-gold-500">
                      <div className="mb-6 rounded-xl overflow-hidden shadow-md">
                        <img src={rhapsodyBannerUrl} alt="Rhapsody of Realities" className="w-full h-auto" />
                      </div>
                      <div className="flex items-center justify-between mb-6 border-b pb-4">
                        <span className="bg-royal-100 text-royal-800 px-3 py-1 rounded-full text-xs font-bold uppercase">Daily Devotional</span>
                        <span className="text-gray-500 font-serif italic">{devotional.date}</span>
                      </div>
                      <h2 className="text-3xl md:text-4xl font-serif font-bold text-royal-950 mb-4">{devotional.title}</h2>
                      <div className="bg-royal-50 p-4 rounded-xl border-l-4 border-royal-500 mb-6 italic text-lg text-royal-800">"{devotional.scripture}"</div>
                      <div className="prose text-gray-700 leading-relaxed font-serif">
                        {devotional.body.split('\n').map((para, i) => <p key={i} className="mb-4">{para}</p>)}
                      </div>
                      <div className="mt-8 pt-8 border-t">
                        <h3 className="text-gold-600 font-bold uppercase text-sm mb-2">Confession</h3>
                        <p className="text-xl font-medium text-royal-900">{devotional.confession}</p>
                      </div>

                      {/* Prominent Download Button Section */}
                      <div className="mt-10 p-6 bg-gradient-to-r from-royal-900 to-royal-800 rounded-2xl text-white shadow-xl flex flex-col md:flex-row items-center justify-between gap-6 border-2 border-gold-500">
                        <div className="flex items-center gap-4">
                          <div className="bg-gold-500 p-3 rounded-full text-royal-950 animate-bounce"><Smartphone size={32} /></div>
                          <div>
                            <h4 className="text-xl font-bold">Never Miss a Day!</h4>
                            <p className="text-sm text-royal-200">Study on the go with the Rhapsody App.</p>
                          </div>
                        </div>
                        <a 
                          href="https://lwappstore.com" 
                          target="_blank" 
                          rel="noopener noreferrer"
                          className="flex items-center gap-2 bg-gold-500 hover:bg-gold-600 text-white px-8 py-3 rounded-full font-black text-lg shadow-lg transform hover:scale-105 transition-all whitespace-nowrap"
                        >
                          <Download size={22} /> DOWNLOAD NOW
                        </a>
                      </div>

                      <div className="mt-10 pt-6 border-t">
                        <h3 className="text-center text-gray-500 font-bold uppercase text-xs mb-4">Share this Rhapsody</h3>
                        <div className="flex flex-wrap justify-center gap-4">
                          <button onClick={() => handleDevotionalShare(SocialPlatform.WhatsApp)} className="flex items-center gap-2 bg-green-500 text-white px-4 py-2 rounded-full transform hover:scale-105 transition-all"><Phone size={18} /> WhatsApp</button>
                          <button onClick={() => handleDevotionalShare(SocialPlatform.Facebook)} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-full transform hover:scale-105 transition-all"><Facebook size={18} /> Facebook</button>
                          <button onClick={() => handleDevotionalShare(SocialPlatform.Twitter)} className="flex items-center gap-2 bg-sky-500 text-white px-4 py-2 rounded-full transform hover:scale-105 transition-all"><Twitter size={18} /> Twitter</button>
                        </div>
                      </div>
                    </article>
                    <GalleryAndShare />
                  </div>
                  <div className="space-y-6">
                    <div className="bg-white/95 backdrop-blur-sm p-6 rounded-xl shadow-lg text-center border">
                      <div className="w-24 h-24 mx-auto rounded-full overflow-hidden mb-4 border-4 border-gold-500"><img src={pastorChrisImageUrl} alt="Pastor Chris" className="w-full h-full object-cover" /></div>
                      <h3 className="font-bold text-xl text-royal-900">Pastor Chris Oyakhilome</h3>
                      <p className="text-sm text-gray-500 mb-4">Author, Rhapsody of Realities</p>
                      <button onClick={() => { setSearchQuery("Pastor Chris Books"); handleSearch({ preventDefault: () => {} } as React.FormEvent); }} className="w-full bg-royal-900 text-white py-2 rounded-full text-sm font-medium hover:bg-royal-800">View Books</button>
                    </div>
                  </div>
                </div>
              ) : null}
            </div>
          )}
          {currentView === 'books' && (
            <div className="max-w-6xl mx-auto">
              <div className="flex items-center justify-between mb-8 text-white"><h2 className="text-3xl font-serif font-bold">Books by Pastor Chris</h2><button onClick={() => setCurrentView('daily')}>&larr; Back</button></div>
              {isSearching ? <div className="flex justify-center py-20"><div className="animate-spin rounded-full h-12 w-12 border-t-4 border-white"></div></div> : <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{searchResults.map(book => <div key={book.id} className="bg-white rounded-xl shadow-lg overflow-hidden"><img src={book.coverUrl} alt={book.title} className="w-full h-48 object-cover" /><div className="p-4"><h3 className="font-bold text-lg">{book.title}</h3><p className="text-sm text-gray-600 line-clamp-2 mt-2">{book.description}</p></div></div>)}</div>}
            </div>
          )}
        </main>

        <footer className="bg-gray-900/95 text-gray-400 py-12 border-t border-gray-800">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-2xl font-serif font-bold text-gold-500 mb-4">THE LAST MAN</h2>
            <p className="max-w-2xl mx-auto mb-8 text-sm">Providing divine insights for the end times. Connect with the Spirit of God daily through the Rhapsody of Realities.</p>
            <div className="text-xs text-gray-600">&copy; {new Date().getFullYear()} THE LAST MAN. All Rights Reserved.</div>
          </div>
        </footer>

        <PrayerOverlay isOpen={showPrayer} onClose={() => setShowPrayer(false)} onAdminNotify={() => setShowNotification({ message: "Praise God! Notification sent.", type: "social" })} />
      </div>
    </div>
  );
}

export default App;